### ISSUE TITLE
[Core Protocol] Example of how to upgrade Proposer or Challenger addresses in L2OutputOracle.sol?

### ISSUE THREAD

**Issue by RnkSngh** [ethereum-optimism/developers#259]
### Discussed in https://github.com/ethereum-optimism/developers/discussions/258

<div type='discussions-op-text'>

<sup>Originally posted by **RnkSngh** February 26, 2024</sup>
### Did you check the documentation?

- [X] Yes

### Did you read the specs?

- [X] Yes
- [ ] No

### Did you check for duplicate questions?

- [X] Yes

### Issue Description

I was looking through the [L2OutputOracle.sol](https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/src/L1/L2OutputOracle.sol) and on [this line](https://github.com/ethereum-optimism/optimism/blob/416cdccd2a93f83fe713dea3b0d86889c430dce3/packages/contracts-bedrock/src/L1/L2OutputOracle.sol#L36) the comment says the address of the Proposer can be updated via upgrade. It also says something similar for the Challenger. 

I was curious how an example of updating either address would look like? Is it basically upgrading to a new L2OutputOracle logic contract that has a setter function to set a new Proposer/Challenger? If so, why is this comment only present on the Challenger and Proposer variables (presumably you can do the same to all other variables stored in the contract) ? 

### Feedback

_No response_</div>

**Comment by sbvegan** [comment]
answered here https://github.com/ethereum-optimism/developers/discussions/258
